using System.ComponentModel;
using ContainerLoader.Exceptions;
using ContainerLoader.Products;


namespace ContainerLoader.Containers;

//
//      The mass of the cargo (in kilograms)
//      Height (in centimeters)
//      Tare weight (the weight of the container itself, in kilograms)
//      Depth (in centimeters)
//      Serial number
// The format of the number is KON-C-1
// The first part of the number is always "KON"
// The second part represents the type of container
// The third part is a number. Numbers should be unique.
// There should be no possibility of two containers having the same number.
// Numbers should be generated by the system.
//      The maximum payload of a given container in kilograms

public abstract class Container 
{

    public double CargoMass { get; set; }
    public double Height { get; set; }
    public double TareWeight { get; set; }
    public double Depth { get; set; }
    public string SerialNumber { get; set; }
    public double MaxPayload { get; set; }


    protected Container( double height, double tareWeight, double depth, string serialNumber, double maxPayload)
    {
        Height = height;
        TareWeight = tareWeight;
        Depth = depth;
        SerialNumber = serialNumber;
        MaxPayload = maxPayload;
    }


    public virtual void Load(Product addedProduct){ }
    
    public virtual void Unload() { }
}